version: '3'

silent: true

includes:
  version:
    taskfile: .taskfile/version.yml
  rust:
    taskfile: .taskfile/rust.yml
  utils:
    taskfile: .taskfile/utils.yml

tasks:
  run:test:
    cmds:
      - cargo run --manifest-path crates/pillar-test/Cargo.toml
