use std::sync::Arc;
use arrow::datatypes::{Field, FieldRef};

use crate::{
    errors::Error,
    value::Value,
    condition::ConditionExpression,
    ast::{refs::ColumnRef, schema::{ColumnDefinition, ColumnType}},
};


/// Compile-time metadata for a single column on a [`Model`](crate::model::Model) or [`View`](crate::view::View).
#[derive(Debug, Clone)]
pub struct ColumnDef {
    pub name: &'static str,
    pub column_type: ColumnType,
    pub nullable: bool,
    pub primary_key: bool,
    pub unique: bool,
    pub default: Option<Value>,
}

impl ColumnDef {
    /// Converts this column definition into an Arrow [`Field`](arrow::datatypes::Field).
    ///
    /// Returns an error if the column type has no valid Arrow representation.
    pub fn to_arrow_field(&self) -> Result<FieldRef, Error> {
        Ok(Arc::new(Field::new(
            self.name,
            self.column_type.to_arrow_data_type()?,
            self.nullable,
        )))
    }
}

impl From<&ColumnDef> for ColumnDefinition {
    fn from(col: &ColumnDef) -> Self {
        Self {
            name: col.name.into(),
            data_type: col.column_type.clone(),
            nullable: col.nullable,
            primary_key: col.primary_key,
            unique: col.unique,
            default: col.default.clone(),
        }
    }
}

/// A typed reference to a column, generated by the `Column` struct in a companion module.
///
/// Carries the column name at compile time and exposes comparison methods that return
/// [`ConditionExpression`](crate::condition::ConditionExpression) values.
///
/// ```rust
/// # use pillar_core::column::TypedColumn;
/// let col: TypedColumn<i32> = TypedColumn::new("severity");
/// ```
#[derive(Debug, Clone, Copy)]
pub struct TypedColumn<T> {
    name: &'static str,
    _marker: std::marker::PhantomData<T>,
}

impl<T> TypedColumn<T> {
    /// Creates a new [`TypedColumn`](crate::column::TypedColumn) with the given column name.
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            _marker: std::marker::PhantomData,
        }
    }

    /// Returns the column name.
    pub fn name(&self) -> &'static str {
        self.name
    }
}

impl<T> From<TypedColumn<T>> for ColumnRef {
    fn from(col: TypedColumn<T>) -> Self {
        ColumnRef::new(col.name)
    }
}

impl<T> TypedColumn<T>
where
    T: Into<Value>,
{
    /// Column equals value.
    pub fn eq<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::eq(self, value.into())
    }

    /// Column does not equal value.
    pub fn ne<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::ne(self, value.into())
    }

    /// Column is greater than value.
    pub fn gt<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::gt(self, value.into())
    }

    /// Column is greater than or equal to value.
    pub fn gte<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::gte(self, value.into())
    }

    /// Column is less than value.
    pub fn lt<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::lt(self, value.into())
    }

    /// Column is less than or equal to value.
    pub fn lte<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::lte(self, value.into())
    }

    /// Column value is in the given list.
    pub fn in_list<I, V>(self, values: I) -> ConditionExpression
    where
        I: IntoIterator<Item = V>,
        V: Into<Value>,
    {
        ConditionExpression::in_list(self, values.into_iter().map(Into::into).collect())
    }

    /// Column value is not in the given list.
    pub fn is_not_in<I, V>(self, values: I) -> ConditionExpression
    where
        I: IntoIterator<Item = V>,
        V: Into<Value>,
    {
        ConditionExpression::is_not_in(self, values.into_iter().map(Into::into).collect())
    }

    /// Column is NULL.
    pub fn is_null(self) -> ConditionExpression {
        ConditionExpression::is_null(self)
    }

    /// Column is not NULL.
    pub fn is_not_null(self) -> ConditionExpression {
        ConditionExpression::is_not_null(self)
    }

    /// Column value is between `low` and `high` (inclusive).
    pub fn between<V: Into<Value>>(self, low: V, high: V) -> ConditionExpression {
        ConditionExpression::between(self, low.into(), high.into())
    }

    /// Column value is not between `low` and `high`.
    pub fn not_between<V: Into<Value>>(self, low: V, high: V) -> ConditionExpression {
        ConditionExpression::not_between(self, low.into(), high.into())
    }
}

impl<T> TypedColumn<T>
where
    T: AsRef<str>,
{
    /// Column value matches the given SQL LIKE pattern.
    pub fn like(self, pattern: impl Into<String>) -> ConditionExpression {
        ConditionExpression::like(self, pattern.into())
    }

    /// Column value does not match the given SQL LIKE pattern.
    pub fn not_like(self, pattern: impl Into<String>) -> ConditionExpression {
        ConditionExpression::not_like(self, pattern.into())
    }
}
