use crate::{
    value::Value,
    condition::ConditionExpression,
    ast::schema::{ColumnDefinition, ColumnType},
};


/// Compile-time metadata for a single column on a [`Model`](crate::model::Model) or [`MaterializedView`](crate::view::MaterializedView).
#[derive(Debug, Clone)]
pub struct ColumnDef {
    pub name: &'static str,
    pub column_type: ColumnType,
    pub nullable: bool,
    pub primary_key: bool,
    pub unique: bool,
    pub default: Option<Value>,
}

impl From<&ColumnDef> for ColumnDefinition {
    fn from(col: &ColumnDef) -> Self {
        Self {
            name: col.name.to_string(),
            data_type: col.column_type.clone(),
            nullable: col.nullable,
            primary_key: col.primary_key,
            unique: col.unique,
            default: col.default.clone(),
        }
    }
}

/// Converts a value into a column name string for use in a query.
pub trait IntoColumnRef {
    fn into_column_ref(self) -> String;
}

impl IntoColumnRef for String {
    fn into_column_ref(self) -> String {
        self
    }
}

impl IntoColumnRef for &String {
    fn into_column_ref(self) -> String {
        self.clone()
    }
}

impl IntoColumnRef for &str {
    fn into_column_ref(self) -> String {
        self.to_string()
    }
}

/// A typed reference to a column, generated by the `Column` struct in a companion module.
///
/// Carries the column name at compile time and exposes comparison methods that return
/// [`ConditionExpression`](crate::condition::ConditionExpression) values.
///
/// ```rust
/// # use pillar_core::column::TypedColumn;
/// let col: TypedColumn<i32> = TypedColumn::new("severity");
/// ```
#[derive(Debug, Clone, Copy)]
pub struct TypedColumn<T> {
    name: &'static str,
    _marker: std::marker::PhantomData<T>,
}

impl<T> TypedColumn<T> {
    /// Creates a new [`TypedColumn`](crate::column::TypedColumn) with the given column name.
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            _marker: std::marker::PhantomData,
        }
    }

    /// Returns the column name.
    pub fn name(&self) -> &'static str {
        self.name
    }
}

impl<T> IntoColumnRef for TypedColumn<T> {
    fn into_column_ref(self) -> String {
        self.name.to_string()
    }
}

impl<T> TypedColumn<T>
where
    T: Into<Value>,
{
    /// Column equals value.
    pub fn eq<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::eq(self.into_column_ref(), value.into())
    }

    /// Column does not equal value.
    pub fn ne<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::ne(self.into_column_ref(), value.into())
    }

    /// Column is greater than value.
    pub fn gt<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::gt(self.into_column_ref(), value.into())
    }

    /// Column is greater than or equal to value.
    pub fn gte<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::gte(self.into_column_ref(), value.into())
    }

    /// Column is less than value.
    pub fn lt<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::lt(self.into_column_ref(), value.into())
    }

    /// Column is less than or equal to value.
    pub fn lte<V: Into<Value>>(self, value: V) -> ConditionExpression {
        ConditionExpression::lte(self.into_column_ref(), value.into())
    }

    /// Column value is in the given list.
    pub fn in_list<I, V>(self, values: I) -> ConditionExpression
    where
        I: IntoIterator<Item = V>,
        V: Into<Value>,
    {
        ConditionExpression::in_list(self.into_column_ref(), values.into_iter().map(Into::into).collect())
    }

    /// Column value is not in the given list.
    pub fn is_not_in<I, V>(self, values: I) -> ConditionExpression
    where
        I: IntoIterator<Item = V>,
        V: Into<Value>,
    {
        ConditionExpression::is_not_in(self.into_column_ref(), values.into_iter().map(Into::into).collect())
    }

    /// Column is NULL.
    pub fn is_null(self) -> ConditionExpression {
        ConditionExpression::is_null(self.into_column_ref())
    }

    /// Column is not NULL.
    pub fn is_not_null(self) -> ConditionExpression {
        ConditionExpression::is_not_null(self.into_column_ref())
    }

    /// Column value is between `low` and `high` (inclusive).
    pub fn between<V: Into<Value>>(self, low: V, high: V) -> ConditionExpression {
        ConditionExpression::between(self.into_column_ref(), low.into(), high.into())
    }

    /// Column value is not between `low` and `high`.
    pub fn not_between<V: Into<Value>>(self, low: V, high: V) -> ConditionExpression {
        ConditionExpression::not_between(self.into_column_ref(), low.into(), high.into())
    }
}

impl<T> TypedColumn<T>
where
    T: AsRef<str>,
{
    /// Column value matches the given SQL LIKE pattern.
    pub fn like(self, pattern: impl Into<String>) -> ConditionExpression {
        ConditionExpression::like(self.into_column_ref(), pattern.into())
    }

    /// Column value does not match the given SQL LIKE pattern.
    pub fn not_like(self, pattern: impl Into<String>) -> ConditionExpression {
        ConditionExpression::not_like(self.into_column_ref(), pattern.into())
    }
}
